Add integer support to linear regression (#484)
* Add integer support to linear regression

* Fix for MSVC error C2668: 'fpclassify' [CI SKIP]

* Fix naming [CI SKIP]